"""create initial tables

Revision ID: 46cb6ea4cf1b
Revises: 
Create Date: 2026-09-13 18:50:53.580271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46cb6ea4cf1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer', 'part_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('mileage >= 0', name='check_vehicle_mileage_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index('ix_vehicles_user_id', 'vehicles', ['user_id'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('service_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('labor_cost >= 0', name='check_labor_cost_non_negative'),
    sa.CheckConstraint('mileage >= 0', name='check_maintenance_mileage_non_negative'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maintenance_records_vehicle_id', 'maintenance_records', ['vehicle_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_record_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expense_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='check_expense_amount_non_negative'),
    sa.ForeignKeyConstraint(['maintenance_record_id'], ['maintenance_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_maintenance_record_id', 'expenses', ['maintenance_record_id'], unique=False)
    op.create_index('ix_expenses_vehicle_id', 'expenses', ['vehicle_id'], unique=False)
    op.create_table('maintenance_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_record_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='check_quantity_positive'),
    sa.CheckConstraint('unit_cost >= 0', name='check_unit_cost_non_negative'),
    sa.ForeignKeyConstraint(['maintenance_record_id'], ['maintenance_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('maintenance_record_id', 'part_id')
    )
    op.create_index('ix_maintenance_parts_maintenance_record_id', 'maintenance_parts', ['maintenance_record_id'], unique=False)
    op.create_index('ix_maintenance_parts_part_id', 'maintenance_parts', ['part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_maintenance_parts_part_id', table_name='maintenance_parts')
    op.drop_index('ix_maintenance_parts_maintenance_record_id', table_name='maintenance_parts')
    op.drop_table('maintenance_parts')
    op.drop_index('ix_expenses_vehicle_id', table_name='expenses')
    op.drop_index('ix_expenses_maintenance_record_id', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_maintenance_records_vehicle_id', table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index('ix_vehicles_user_id', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('parts')
    # ### end Alembic commands ###
