"""add vehicle verification status

Revision ID: b677b44ab9b4
Revises: 7b6688d2c486
Create Date: 2026-09-22 21:54:22.995935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b677b44ab9b4'
down_revision: Union[str, Sequence[str], None] = '7b6688d2c486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "vehicles",
        sa.Column("verified", sa.Boolean(), nullable=True),
    )

    op.execute(
        "UPDATE vehicles SET verified = TRUE"
    )

    op.alter_column(
        "vehicles",
        "verified",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'verified')
    # ### end Alembic commands ###
