"""add payments table

Revision ID: bd64065dfd22
Revises: 1dbaf8c4ccd3
Create Date: 2026-09-27 16:08:42.397400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd64065dfd22'
down_revision: Union[str, Sequence[str], None] = '1dbaf8c4ccd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_record_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'paid', 'failed', 'expired')", name='check_payment_status'),
    sa.CheckConstraint('amount >= 0', name='check_payment_amount_non_negative'),
    sa.ForeignKeyConstraint(['maintenance_record_id'], ['maintenance_records.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_maintenance_record_id', 'payments', ['maintenance_record_id'], unique=False)
    op.create_index('ix_payments_stripe_checkout_session_id', 'payments', ['stripe_checkout_session_id'], unique=False)
    op.create_index('ix_payments_stripe_payment_intent_id', 'payments', ['stripe_payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_stripe_payment_intent_id', table_name='payments')
    op.drop_index('ix_payments_stripe_checkout_session_id', table_name='payments')
    op.drop_index('ix_payments_maintenance_record_id', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
